export interface RawQuestion {
  text: string
  options: [string, string, string, string]
  correctIndex: 0 | 1 | 2 | 3
}

export const QUESTIONS: RawQuestion[] = [
  { text: "Which planet is closest to the Sun?", options: ["Venus", "Mercury", "Mars", "Earth"], correctIndex: 1 },
  { text: "What is the largest mammal on Earth?", options: ["African elephant", "Blue whale", "Giraffe", "Orca"], correctIndex: 1 },
  { text: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], correctIndex: 2 },
  { text: "Which country invented tea?", options: ["India", "Japan", "England", "China"], correctIndex: 3 },
  { text: "What does 'www' stand for?", options: ["World Wide Web", "Wide World Web", "Web World Wide", "World Web Wide"], correctIndex: 0 },
  { text: "Which animal can sleep for three years?", options: ["Sloth", "Snail", "Bear", "Koala"], correctIndex: 1 },
  { text: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctIndex: 2 },
  { text: "How many bones does an adult human have?", options: ["186", "206", "226", "246"], correctIndex: 1 },
  { text: "Which ocean is the deepest?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctIndex: 3 },
  { text: "What color do you get when you mix blue and yellow?", options: ["Green", "Purple", "Orange", "Brown"], correctIndex: 0 },
  { text: "Who painted the Mona Lisa?", options: ["Van Gogh", "Picasso", "Da Vinci", "Rembrandt"], correctIndex: 2 },
  { text: "What is the smallest country in the world?", options: ["Monaco", "Nauru", "San Marino", "Vatican City"], correctIndex: 3 },
  { text: "How many minutes are in a full day?", options: ["1200", "1440", "1600", "2400"], correctIndex: 1 },
  { text: "Which metal is liquid at room temperature?", options: ["Mercury", "Lead", "Tin", "Zinc"], correctIndex: 0 },
  { text: "What is the tallest mountain in the world?", options: ["K2", "Everest", "Denali", "Kilimanjaro"], correctIndex: 1 },
  { text: "Which sport uses a shuttlecock?", options: ["Squash", "Badminton", "Table tennis", "Padel"], correctIndex: 1 },
  { text: "How many hearts does an octopus have?", options: ["1", "2", "3", "8"], correctIndex: 2 },
  { text: "What is the hardest natural substance?", options: ["Quartz", "Steel", "Diamond", "Titanium"], correctIndex: 2 },
  { text: "Which language has the most native speakers?", options: ["English", "Spanish", "Hindi", "Mandarin Chinese"], correctIndex: 3 },
  { text: "What year did the first iPhone launch?", options: ["2006", "2007", "2008", "2009"], correctIndex: 1 },
  { text: "Which fruit has its seeds on the outside?", options: ["Kiwi", "Strawberry", "Banana", "Plum"], correctIndex: 1 },
  { text: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctIndex: 1 },
  { text: "What is the fastest land animal?", options: ["Lion", "Cheetah", "Pronghorn", "Greyhound"], correctIndex: 1 },
  { text: "Which element has the symbol 'Au'?", options: ["Silver", "Aluminium", "Gold", "Argon"], correctIndex: 2 },
  { text: "Where were the first modern Olympic Games held?", options: ["Paris", "London", "Athens", "Rome"], correctIndex: 2 },
  { text: "What do bees collect to make honey?", options: ["Pollen", "Nectar", "Dew", "Sap"], correctIndex: 1 },
  { text: "Which is the only continent without native ants?", options: ["Europe", "Australia", "Antarctica", "South America"], correctIndex: 2 },
  { text: "How many keys does a standard piano have?", options: ["76", "84", "88", "96"], correctIndex: 2 },
  { text: "What is the main ingredient in guacamole?", options: ["Peas", "Avocado", "Zucchini", "Kiwi"], correctIndex: 1 },
  { text: "Which bird cannot fly?", options: ["Eagle", "Penguin", "Swan", "Crow"], correctIndex: 1 },
  { text: "What does DNA stand for?", options: ["Deoxyribonucleic acid", "Dinucleic acid", "Dual nucleic acid", "Deoxy nitro acid"], correctIndex: 0 },
  { text: "Which country has the most time zones?", options: ["USA", "Russia", "France", "China"], correctIndex: 2 },
  { text: "What is the fear of heights called?", options: ["Claustrophobia", "Acrophobia", "Arachnophobia", "Hydrophobia"], correctIndex: 1 },
  { text: "How many players are on a soccer team on the field?", options: ["9", "10", "11", "12"], correctIndex: 2 },
  { text: "Which gas do plants absorb from the air?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correctIndex: 2 },
  { text: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctIndex: 0 },
  { text: "Which shape has no sides?", options: ["Triangle", "Circle", "Square", "Pentagon"], correctIndex: 1 },
  { text: "What is the currency of Japan?", options: ["Won", "Yuan", "Yen", "Ringgit"], correctIndex: 2 },
  { text: "How many colors are in a rainbow (traditionally)?", options: ["5", "6", "7", "8"], correctIndex: 2 },
  { text: "Which animal is known as the 'King of the Jungle'?", options: ["Tiger", "Lion", "Gorilla", "Elephant"], correctIndex: 1 },
  { text: "What is 15% of 200?", options: ["25", "30", "35", "40"], correctIndex: 1 },
  { text: "Which planet has the most rings?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], correctIndex: 1 },
  { text: "What fruit is used to make wine traditionally?", options: ["Apple", "Grapes", "Cherry", "Plum"], correctIndex: 1 },
  { text: "How many continents are there?", options: ["5", "6", "7", "8"], correctIndex: 2 },
  { text: "Which sea creature has eight arms?", options: ["Squid", "Octopus", "Cuttlefish", "Starfish"], correctIndex: 1 },
  { text: "What is the boiling point of water in Celsius?", options: ["90", "95", "100", "110"], correctIndex: 2 },
  { text: "Who wrote 'Romeo and Juliet'?", options: ["Dickens", "Shakespeare", "Chaucer", "Austen"], correctIndex: 1 },
  { text: "Which is the largest desert in the world?", options: ["Sahara", "Gobi", "Antarctic Desert", "Arabian Desert"], correctIndex: 2 },
]
