export type CategoryId =
  | "funny"
  | "weird"
  | "life"
  | "fantasy"
  | "scifi"
  | "money"
  | "relationships"
  | "survival";

export const CATEGORY_META: Record<CategoryId, { label: string; emoji: string }> = {
  funny: { label: "Funny", emoji: "😂" },
  weird: { label: "Weird", emoji: "🤨" },
  life: { label: "Life Choices", emoji: "🌱" },
  fantasy: { label: "Fantasy", emoji: "🐉" },
  scifi: { label: "Sci-Fi", emoji: "🚀" },
  money: { label: "Money", emoji: "💰" },
  relationships: { label: "Relationships", emoji: "💞" },
  survival: { label: "Survival", emoji: "🏕️" },
};

export const OPTIONS: Record<CategoryId, string[]> = {
  funny: [
    "A pet dragon the size of a chihuahua",
    "A robot that only tells terrible jokes",
    "Sneezing glitter forever",
    "Burping confetti on command",
    "A talking dog that critiques your outfits",
    "Free pizza for life, pineapple-only",
    "A clone of you that does your chores",
    "Hair that styles itself every morning",
    "A fridge that restocks itself",
    "Socks that never slide down",
    "A parrot that gossips about the neighbours",
    "Winning rock-paper-scissors every time",
    "A trampoline instead of an office chair",
    "Farting in Morse code",
    "A washing machine that also folds laundry",
    "Famous for one weird viral video",
    "A theme song playing whenever you enter a room",
    "Laughing in car-horn sounds",
    "A remote that skips awkward moments",
    "An umbrella that predicts rain perfectly",
    "Shoes that tie their own laces",
    "A cat that actually pays rent",
    "Teleporting, but only sideways",
    "Turning invisible for 10 minutes a day",
    "Every meal tasting like dessert",
    "A mirror that compliments you daily",
    "An alarm clock that makes pancakes",
    "Never needing a Wi-Fi password again",
    "A tiny elephant bodyguard",
    "A voice like a movie-trailer narrator",
    "Pigeons delivering your texts",
    "A lawn that mows itself",
    "Yawning in surround sound",
    "A doorbell that scares off telemarketers",
    "Chappals that never flip-flop away",
    "Auto-correct that is always polite",
  ],
  weird: [
    "Sneezing every time you lie",
    "Your shadow moving two seconds late",
    "Everything you draw turns slightly ugly",
    "Speaking only in rhymes after sunset",
    "Doors that squeak opera music",
    "Rain that smells like popcorn",
    "Your reflection waving before you do",
    "Chairs that adjust themselves moodily",
    "Gravity napping every Sunday",
    "Birds delivering spam mail",
    "Stairs counting their steps out loud",
    "Soup humming while it cools",
    "Clouds shaped like your ex",
    "Clocks gossiping about time zones",
    "Elevator music following you outdoors",
    "The left shoe always slightly damp",
    "The moon visible only at noon",
    "Texts arriving as smoke signals",
    "Plants rolling their eyes at you",
    "Mirrors adding exactly three kilos",
    "Pens that write tomorrow's weather",
    "Toast landing butter-side up forever",
    "Echoes answering your questions",
    "Shadows doing jazz hands",
    "Furniture rearranging itself when bored",
    "Wind whispering movie spoilers",
    "Rain falling upward once a week",
    "Streetlights flickering your name",
    "Lost socks reappearing from nowhere",
    "Kettles hitting opera high notes",
    "Candles blowing themselves out politely",
    "Snail races broadcast live on TV",
    "Your laugh echoing three times",
    "Umbrellas attracting only light drizzle",
    "Wi-Fi that works only while dancing",
    "Traffic lights judging your outfit",
  ],
  life: [
    "Never waiting in traffic again",
    "Reading ten times faster",
    "Free coffee for life",
    "A job you love at half the salary",
    "Four-day work weeks forever",
    "A perfect sense of direction",
    "Never feeling awkward again",
    "Waking up at 5 AM naturally",
    "One close friend in every city",
    "Never losing your keys",
    "Cooking like a master chef",
    "Inbox zero forever",
    "A home with zero clutter",
    "Remembering everyone's names",
    "Falling asleep anywhere in 60 seconds",
    "Never getting sick again",
    "One extra hour added to every day",
    "Perfect posture without trying",
    "Hot water that never runs out",
    "Growing all your own food",
    "Living next to your best friend",
    "Working from a beach town",
    "Retiring at 40",
    "Public speaking without fear",
    "Toast that never burns",
    "Finding money in old jackets monthly",
    "The perfect parking spot, always",
    "Never dropping your phone",
    "Meeting your hero over dinner",
    "Learning any language instantly",
    "Never needing sleep",
    "Airport security lines skipped forever",
    "A cabin in the mountains",
    "A garden that never dies",
    "Never forgetting a password",
    "Mondays feeling like Fridays",
  ],
  fantasy: [
    "Flying, but only two metres high",
    "Invisible whenever nobody watches",
    "A wand with one spell left",
    "Talking to cats (they're rude)",
    "A treasure map that actually works",
    "Living in a treehouse castle",
    "Riding a griffin to work",
    "A luck potion every morning",
    "Dragons hoarding compliments instead of gold",
    "A sword that makes perfect toast",
    "Shoes enchanted to dance for you",
    "An owl familiar that judges you",
    "Mermaid friends who gossip about sailors",
    "Wizard school night classes",
    "A crystal ball showing tomorrow's lunch",
    "Unicorns delivering your parcels",
    "A genie who grants only snacks",
    "Ghost roommates who clean up",
    "A talking sword with stage fright",
    "Furniture crafted by elves",
    "Sleeping potions replacing alarm clocks",
    "A phoenix-shaped desk lamp",
    "A spell that folds laundry",
    "Trolls under bridges charging hugs as tolls",
    "A fairy godmother with poor Wi-Fi",
    "A bottomless bowl of soup",
    "Gargoyle security guards",
    "Magic beans (actually just beans)",
    "A cauldron brewing perfect chai",
    "Werewolf-led moonlight yoga",
    "Broomsticks with turn signals",
    "Enchanted mirrors giving pep talks",
    "A dragon egg incubator",
    "Castles with self-cleaning moats",
    "A cloak of mild politeness",
    "Fairy lights powered by actual fairies",
  ],
  scifi: [
    "Living on Mars",
    "Living in an underwater city",
    "A robot twin who attends boring meetings",
    "Teleporting to work",
    "Backing up your memories nightly",
    "An AI assistant stuck in sarcasm mode",
    "A spaceship with terrible fuel economy",
    "Time slowing down when you nap",
    "A cybernetic arm with a bottle opener",
    "Colonising Jupiter's moons",
    "Holographic pet dinosaurs",
    "Self-driving everything",
    "Downloading skills straight into your brain",
    "A space-elevator commute",
    "Robot baristas remembering your order",
    "Anti-gravity basketball leagues",
    "Weather control limited to your street",
    "A personal force field",
    "Laser tag becoming an Olympic sport",
    "Nanobots tidying your room",
    "Mars influencer culture",
    "Cryosleep that skips Mondays",
    "Universal translators for pets",
    "Hoverboards that obey traffic rules",
    "An asteroid-mining side hustle",
    "Solar-powered everything",
    "Mecha suits for gardening",
    "Quantum dating apps",
    "Weekends at orbital hotels",
    "Robot therapists cheaper than humans",
    "Telepathic group chats",
    "Fusion-powered skateboards",
    "AI poets rivaling humans",
    "Warp-speed food delivery",
    "Digital immortality (cloud-based)",
    "Printer technology that still never works",
  ],
  money: [
    "₹100 right now",
    "₹1,000 next month",
    "₹10,000 today",
    "₹50,000 in a year",
    "Double salary",
    "Half working hours",
    "Rich and unknown",
    "Famous and broke",
    "A mansion far from everything",
    "A cosy flat in the city centre",
    "Free flights for life",
    "Free hotels for life",
    "A ₹1 lakh bonus",
    "20 extra paid leaves",
    "50% off everything forever",
    "10% cashback on everything",
    "Finding ₹500 weekly in old jackets",
    "Rent-free living with pigeon roommates",
    "A piggy bank that fights back",
    "Being paid in tiny diamonds",
    "An ATM that dispenses coupons",
    "Investing in moon real estate",
    "EMI-free life with no online shopping",
    "A wallet that blocks impulse buys",
    "UPI payments via interpretive dance",
    "Stock tips from fortune cookies",
    "Free petrol for life",
    "Free internet for life",
    "A CA who doubles as a stand-up comic",
    "Gold bars too heavy to lift",
    "A lottery paying out in pizza slices",
    "Interest rates decided by coin flips",
    "An emergency fund that purrs",
    "Salary doubled but the boss is a dragon",
    "A raise paid entirely in leave days",
    "Crypto made of actual coins",
    "A bank whose queues tell jokes",
    "Winning ₹10 crore but amnesia for 10 years",
    "Groceries free forever but you must cook",
    "A credit card that judges purchases aloud",
    "Getting pocket money from a robot grandma",
    "Zero bills but zero privacy",
    "A money tree that grows one leaf a year",
    "Cashback in hugs (negotiable rate)",
    "Rent paid in houseplants",
  ],
  relationships: [
    "A partner who's brutally honest",
    "A partner who's endlessly kind",
    "A best friend who listens",
    "A best friend who advises",
    "Weekly family dinners",
    "Monthly family road trips",
    "Love letters",
    "Voice notes",
    "Sharing one dessert",
    "Always ordering two desserts",
    "A partner who cooks",
    "A partner who cleans",
    "Long distance with sweet visits",
    "Nearby but always busy",
    "Meeting the parents first",
    "Meeting the pet first",
    "Arguments settled by board games",
    "Anniversary trips planned by your partner",
    "A soulmate who snores gloriously",
    "Family group chats you can't mute",
    "A wedding with just 20 guests",
    "A wedding with 200 guests",
    "A partner who remembers every date",
    "A partner who surprises randomly",
    "Reuniting with a friend after 10 years",
    "Neighbours who bake constantly",
    "Neighbours who stay perfectly silent",
    "Assembling IKEA furniture as a team",
    "Settling dog-vs-cat debates forever",
    "Twin telepathy with your sibling",
    "Grandparents' stories on infinite repeat",
    "A tough mentor",
    "A gentle mentor",
    "Roommates with DJ vibes",
    "Roommates with library silence",
    "Date nights at home",
    "Date nights outside",
    "Handwritten notes",
    "Perfect emojis",
    "Apologies delivered via memes",
    "A partner who sings badly and proudly",
    "Friends who show up unannounced",
    "A big fat wedding",
    "Court marriage plus honeymoon",
    "Couple workout sessions",
    "Relationship advice from a five-year-old",
    "A partner who always wins dumb bets",
    "Planning group trips yourself",
    "Letting friends plan group trips",
    "Sibling rivalry settled by chess",
    "In-laws who live next door",
    "In-laws on another continent",
    "A partner who dances anywhere anytime",
    "Best-friend bracelets with GPS",
  ],
  survival: [
    "Jungle survival with a machete",
    "Jungle survival with just a lighter",
    "Desert escape with only a map",
    "Desert escape with a full water bottle",
    "A snow-cave shelter",
    "A lean-to shelter",
    "Fishing with a spear",
    "Fishing with a net",
    "A blazing signal fire",
    "A giant SOS sign",
    "River crossings at dawn",
    "River crossings at dusk",
    "Bear encounters: climb a tree",
    "Bear encounters: play dead",
    "Storm shelter in a dark cave",
    "Storm shelter under dense trees",
    "Three days of food",
    "Three days of water",
    "One trusty knife",
    "One long rope",
    "Sturdy boots",
    "A warm jacket",
    "A box of matches",
    "A magnifying lens",
    "Mountain passes crossed by daylight",
    "Night hikes over frozen passes",
    "An island full of goats",
    "An island full of coconuts",
    "A radio with spare batteries",
    "A flare gun",
    "A first-aid kit",
    "A water filter",
    "Hunting at dawn",
    "Gathering food all day",
    "Sleeping in shifts",
    "Sleeping through the night",
    "Following birds",
    "Following rivers",
    "Rationing food carefully",
    "Foraging for extras",
    "Building a raft",
    "Fixing the old radio",
    "Floods: heading for high ground",
    "Floods: hiding in forest cover",
    "Snake-bite kit in the pack",
    "Extra antiseptic in the pack",
    "Apocalypse in city ruins",
    "Apocalypse in the countryside",
    "Surviving totally solo",
    "Surviving with one teammate",
    "A canned-food cache",
    "A seed vault",
    "Zombie outbreak with sprinters",
    "Zombie outbreak with slow crawlers",
    "A bunker stocked with Netflix",
    "A beach bunker with coconuts",
    "Trading supplies with strangers",
    "Going full stealth mode",
    "A solar charger",
    "A hand-crank radio",
    "Guard duty at midnight",
    "Guard duty at dawn",
    "Trusting the local guide",
    "Trusting the satellite phone",
    "Wilderness chef: open-fire roast",
    "Wilderness chef: one-pot stew",
    "Winter survival: fur blanket",
    "Winter survival: thermal suit",
    "Rescue signal with a mirror",
    "Rescue signal with a whistle",
  ],
};

export const ABSURD_EXTRA: string[] = [
  "Fighting one horse-sized duck",
  "Fighting 100 duck-sized horses",
  "A haircut that regrows daily",
  "Punching clouds (allegedly soft)",
  "Eating soup with a fork forever",
  "Walking on your hands to work",
  "Talking like a pirate every Monday",
  "Sneezing backwards",
  "A tail you must wag politely",
  "Wearing swimming goggles 24/7",
  "Blinking in Morse code",
  "Hiccuping bubbles",
  "Riding a bicycle built for bees",
  "Arms long enough to high-five the moon",
  "Legs whistling while running",
  "Elbows predicting rain",
  "A nose that beeps on demand",
  "Hair that stores snacks",
  "Toes that play piano",
  "Ears folding like origami",
  "Eyebrows with built-in GPS",
  "Teeth doubling as bottle openers",
  "Knees squeaking politely",
  "Fingers glowing during movies",
  "A tongue detecting lies (badly)",
  "A belly button storing loose change",
  "A shadow applauding you",
  "A pet rock with anxiety",
  "A cloud following you like a puppy",
  "A doorbell ringing from the future",
];

export const PROMPTS: string[] = [
  "Would you rather…",
  "No wrong answers…",
  "Pick your pain…",
  "Choose wisely… or not.",
  "Gut decision, GO!",
  "Quick! Choose one!",
  "Two doors. One tap.",
  "Destiny needs input…",
  "Trust your instincts…",
  "Life asked. You answer.",
];

export const REVEAL_QUIPS: string[] = [
  "Bold.",
  "Interesting…",
  "Chaotic energy!",
  "Respect.",
  "Noted. Forever.",
  "The council agrees.",
  "A classic move.",
  "Spicy choice!",
  "Hmm… okay then.",
  "The dragon approves.",
  "Scientifically dubious.",
  "Your therapist knows.",
  "Iconic behaviour.",
  "Absolutely unhinged.",
  "Clean pick!",
];

export const CATEGORY_LABELS = Object.keys(CATEGORY_META) as CategoryId[];
